import sharedActions from '../../shared/constants/SharedConstants';

const filesActions = {
  FETCHING_FILES: 'FETCHING_FILES',
  FETCH_FILES_SUCCESS: 'FETCH_FILES_SUCCESS',
  FETCH_FILES_FAILURE: 'FETCH_FILES_FAILURE',
  DELETING_FILE: 'DELETING_FILE',
  DELETE_FILE_SUCCESS: 'DELETE_FILE_SUCCESS',
  DELETE_FILE_FAILURE: 'DELETE_FILE_FAILURE',
  RENAMING_FILE: 'RENAMING_FILE',
  RENAME_FILE_SUCCESS: 'RENAME_FILE_SUCCESS',
  RENAME_FILE_FAILURE: 'RENAME_FILE_FAILURE',
  MOVING_FILE: 'MOVING_FILE',
  MOVE_FILE_SUCCESS: 'MOVE_FILE_SUCCESS',
  MOVE_FILE_FAILURE: 'MOVE_FILE_FAILURE'
};


const folderlistActions = {
  FETCHING_FOLDERS: 'FETCHING_FOLDERS',
  FETCH_FOLDERS_SUCCESS: 'FETCH_FOLDERS_SUCCESS',
  FETCH_FOLDERS_FAILURE: 'FETCH_FOLDERS_FAILURE',
  CREATING_FOLDER: 'CREATING_FOLDER',
  CREATE_FOLDER_SUCCESS: 'CREATE_FOLDER_SUCCESS',
  CREATE_FOLDER_FAILURE: 'CREATE_FOLDER_FAILURE',
  RENAMING_FOLDER: 'RENAMING_FOLDER',
  RENAME_FOLDER_SUCCESS: 'RENAME_FOLDER_SUCCESS',
  RENAME_FOLDER_FAILURE: 'RENAME_FOLDER_FAILURE'
};

export default { ...filesActions, ...folderlistActions, ...sharedActions };
