const actionTypes = {
  FETCHING_IMPORT_HISTORY: 'FETCHING_IMPORT_HISTORY',
  FETCH_SUCCESS_IMPORT_HISTORY: 'FETCH_SUCCESS_IMPORT_HISTORY',
  FETCH_FAILED_IMPORT_HISTORY: 'FETCH_FAILED_IMPORT_HISTORY',
  FETCH_IMPORT_PROGRESS_SUCCESS: 'FETCH_IMPORT_PROGRESS_SUCCESS',
  RESET_IMPORT_PROGRESS: 'RESET_IMPORT_PROGRESS',
  FETCH_IMPORT_ERROR_SUMMARY_SUCCESS: 'FETCH_IMPORT_ERROR_SUMMARY_SUCCESS',
  GENERATE_IMPORT_ERROR_DETAILS_SUCCESS: 'GENERATE_IMPORT_ERROR_DETAILS_SUCCESS',
  FETCH_IMPORT_ERROR_DETAILS_BY_PAGE_SUCCESS: 'FETCH_IMPORT_ERROR_DETAILS_BY_PAGE_SUCCESS'
};

export default actionTypes;
